# Generated by Django 4.2.5 on 2023-10-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staff_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
