# Generated by Django 4.2.5 on 2023-10-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
