# Generated by Django 4.2.5 on 2023-10-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_data',
            new_name='attendance_date',
        ),
    ]
